export interface JournalRequirements {
  name: string;
  abbreviation: string;
  publisher: string;
  field: string;
  impactFactor: number;
  quartile: 'Q1' | 'Q2' | 'Q3' | 'Q4';
  acceptanceRate: number;
  turnaroundDays: number;
  wordLimits: { abstract: number; main: number; references?: number };
  structure: string[];
  citationStyle: string;
  figureSpecs: { maxFigures: number; format: string; minDPI: number };
  openAccess: { available: boolean; apc?: number; currency?: string };
  peerReviewType: string;
  ethicsRequired: boolean;
  dataAvailabilityRequired: boolean;
  keyRequirements: string[];
  typicalRejectionReasons: string[];
  reviewerFocus: string[];
  coverLetterTips: string[];
  abstractFormat: string;
  website: string;
}

export const JOURNAL_DATABASE: JournalRequirements[] = [
  {
    name: 'Nature',
    abbreviation: 'Nature',
    publisher: 'Springer Nature',
    field: 'Multidisciplinary',
    impactFactor: 64.8,
    quartile: 'Q1',
    acceptanceRate: 0.08,
    turnaroundDays: 60,
    wordLimits: { abstract: 150, main: 3000, references: 50 },
    structure: ['Abstract', 'Introduction', 'Results', 'Discussion', 'Methods', 'References'],
    citationStyle: 'Nature (numbered superscript)',
    figureSpecs: { maxFigures: 8, format: 'PDF/EPS/TIFF', minDPI: 300 },
    openAccess: { available: true, apc: 11690, currency: 'USD' },
    peerReviewType: 'Double-blind',
    ethicsRequired: true,
    dataAvailabilityRequired: true,
    keyRequirements: [
      'Results must represent a major advance, not incremental progress',
      'Maximum 50 references; Letters limited to 30',
      'All primary data must be deposited in a public repository',
      'Statistical reporting checklist mandatory for all papers',
      'CONSORT/PRISMA compliance required for clinical studies',
      'Methods section placed at end of article',
      'Highlights (3 bullet points) required for online abstract',
    ],
    typicalRejectionReasons: [
      'Insufficient novelty or broad scientific significance',
      'Results of interest only to specialists in one sub-field',
      'Incremental advance over previously published work',
      'Sample size insufficient to support conclusions',
      'Missing mechanistic insight for observational findings',
    ],
    reviewerFocus: [
      'Novelty and broad significance across disciplines',
      'Rigor of experimental design and statistical analysis',
      'Reproducibility and data transparency',
      'Clarity of mechanistic explanation',
    ],
    coverLetterTips: [
      'Lead with why this finding matters to scientists outside your field',
      'State explicitly what conceptual advance this represents',
      'Mention 3 specific Nature readers outside your field who would care',
      'Keep to one page; editors read hundreds per day',
    ],
    abstractFormat: 'Unstructured, 150 words max. Must convey the problem, main finding, and significance to non-specialists.',
    website: 'nature.com/nature',
  },
  {
    name: 'Science',
    abbreviation: 'Science',
    publisher: 'AAAS',
    field: 'Multidisciplinary',
    impactFactor: 56.9,
    quartile: 'Q1',
    acceptanceRate: 0.07,
    turnaroundDays: 55,
    wordLimits: { abstract: 125, main: 2500, references: 40 },
    structure: ['Abstract', 'Introduction', 'Results', 'Discussion', 'Materials and Methods'],
    citationStyle: 'Science (numbered)',
    figureSpecs: { maxFigures: 6, format: 'PDF/EPS', minDPI: 300 },
    openAccess: { available: true, apc: 4500, currency: 'USD' },
    peerReviewType: 'Single-blind',
    ethicsRequired: true,
    dataAvailabilityRequired: true,
    keyRequirements: [
      'Reports limited to 2500 words (intro through discussion)',
      'Abstract must be comprehensible to non-specialist in 125 words',
      'Supplementary materials extensively used for methods detail',
      'One-sentence summary (125 characters) required',
      'Materials and Methods placed after Discussion',
    ],
    typicalRejectionReasons: [
      'Lacks broad interest beyond specialist community',
      'Conclusions overstated relative to data presented',
      'Technical advance without conceptual novelty',
      'Insufficient validation of key findings',
    ],
    reviewerFocus: [
      'Broad significance and conceptual novelty',
      'Technical rigor across multiple validation approaches',
      'Clarity of main message for general scientific audience',
    ],
    coverLetterTips: [
      'State your advance in one sentence suitable for a press release',
      'Explain why now — what enabled this discovery',
      'Describe anticipated impact outside your immediate field',
    ],
    abstractFormat: 'Unstructured, 125 words. One sentence each: problem, gap, approach, result, significance.',
    website: 'science.org',
  },
  {
    name: 'The New England Journal of Medicine',
    abbreviation: 'NEJM',
    publisher: 'Massachusetts Medical Society',
    field: 'Medicine (Clinical)',
    impactFactor: 158.5,
    quartile: 'Q1',
    acceptanceRate: 0.05,
    turnaroundDays: 30,
    wordLimits: { abstract: 250, main: 3400, references: 70 },
    structure: ['Structured Abstract', 'Introduction', 'Methods', 'Results', 'Discussion', 'References'],
    citationStyle: 'NEJM (Vancouver, superscript numbers)',
    figureSpecs: { maxFigures: 6, format: 'EPS/TIFF', minDPI: 350 },
    openAccess: { available: false },
    peerReviewType: 'Double-blind',
    ethicsRequired: true,
    dataAvailabilityRequired: true,
    keyRequirements: [
      'Original articles limited to 3400 words, 70 references, 6 figures/tables',
      'Structured abstract: Background, Methods, Results, Conclusions (250 words)',
      'CONSORT diagram mandatory for all RCTs',
      'Pre-registration required for all clinical trials (ClinicalTrials.gov)',
      'ICMJE authorship criteria must be met by all authors',
      'Data sharing statement required; raw data must be available on request',
      'Statistical analysis plan must be pre-specified for primary outcomes',
    ],
    typicalRejectionReasons: [
      'Clinical question not novel or important enough for NEJM readership',
      'Underpowered study; results inconclusive',
      'Pre-registration not completed before study initiation',
      'Conflict of interest not adequately disclosed',
      'Results already published or previewed (embargo violation)',
      'Study design inappropriate for research question',
    ],
    reviewerFocus: [
      'Clinical importance and potential impact on practice guidelines',
      'Methodological rigor (randomization, blinding, allocation concealment)',
      'Adequacy of sample size and power',
      'Appropriate statistical methods for endpoint type',
      'Generalizability and external validity',
    ],
    coverLetterTips: [
      'State clearly how this changes clinical practice or guidelines',
      'Mention if results contradict current standard of care',
      'Highlight any pre-registration and data sharing compliance',
      'Note any accompanying editorial or comment you anticipate',
    ],
    abstractFormat: 'Structured: Background (2 sentences), Methods (3-4 sentences), Results (primary + 2-3 secondary outcomes with numbers), Conclusions (1-2 sentences). 250 words max.',
    website: 'nejm.org',
  },
  {
    name: 'The Lancet',
    abbreviation: 'Lancet',
    publisher: 'Elsevier',
    field: 'Medicine (Clinical)',
    impactFactor: 168.9,
    quartile: 'Q1',
    acceptanceRate: 0.05,
    turnaroundDays: 28,
    wordLimits: { abstract: 250, main: 4200, references: 60 },
    structure: ['Structured Abstract', 'Introduction', 'Methods', 'Results', 'Discussion', 'Contributors', 'Declaration of interests'],
    citationStyle: 'Lancet (Vancouver superscript)',
    figureSpecs: { maxFigures: 6, format: 'EPS/PDF/TIFF', minDPI: 300 },
    openAccess: { available: true, apc: 6400, currency: 'USD' },
    peerReviewType: 'Double-blind',
    ethicsRequired: true,
    dataAvailabilityRequired: true,
    keyRequirements: [
      'Articles: 4200 words, 6 figures/tables, 60 references',
      'Panels and correspondence: 250 words only',
      'Contributor statement required detailing each author\'s role',
      'STROBE/CONSORT compliance mandatory with checklist attached',
      'Funding source and role of funder must be stated explicitly',
      '"Panel" format available for key policy or clinical messages',
    ],
    typicalRejectionReasons: [
      'Limited to high-income countries; insufficient generalizability',
      'Study size too small for the claims made',
      'Methods section lacks detail for reproducibility',
      'Missing CONSORT/STROBE checklist',
      'Results are confirmatory rather than novel',
    ],
    reviewerFocus: [
      'Global health relevance and equity implications',
      'Methodological transparency and reproducibility',
      'Strength and clarity of clinical/policy implications',
      'Adequate adjustment for confounding in observational studies',
    ],
    coverLetterTips: [
      'Frame your question in global health context when possible',
      'State the practice- or policy-changing nature of findings',
      'List any competing submissions and related publications',
    ],
    abstractFormat: 'Structured: Background, Methods, Findings (use "Findings" not "Results"), Interpretation. 250 words. Note: Lancet uses "Findings" not "Results".',
    website: 'thelancet.com',
  },
  {
    name: 'JAMA (Journal of the American Medical Association)',
    abbreviation: 'JAMA',
    publisher: 'AMA',
    field: 'Medicine (Clinical)',
    impactFactor: 120.7,
    quartile: 'Q1',
    acceptanceRate: 0.05,
    turnaroundDays: 30,
    wordLimits: { abstract: 350, main: 3000, references: 120 },
    structure: ['Structured Abstract', 'Introduction', 'Methods', 'Results', 'Discussion', 'Conclusions'],
    citationStyle: 'JAMA (AMA style)',
    figureSpecs: { maxFigures: 5, format: 'EPS/TIFF', minDPI: 300 },
    openAccess: { available: true, apc: 3500, currency: 'USD' },
    peerReviewType: 'Double-blind',
    ethicsRequired: true,
    dataAvailabilityRequired: true,
    keyRequirements: [
      'Conclusions section is mandatory (separate from Discussion)',
      'AMA Manual of Style required for all formatting',
      'Statistical analysis requires a named statistician as author or acknowledgment',
      'Reporting guidelines checklist must accompany all manuscripts',
      'Study limitations must be explicit in final Discussion paragraph',
    ],
    typicalRejectionReasons: [
      'Findings not actionable for clinicians',
      'Retrospective design when prospective data exists',
      'Statistical methodology not clearly explained',
      'Conclusions exceed what data support',
    ],
    reviewerFocus: [
      'Clinical actionability and guideline implications',
      'Quality of statistical methodology',
      'Completeness of reporting per EQUATOR guidelines',
      'Transparent conflict of interest handling',
    ],
    coverLetterTips: [
      'Explicitly state how findings should change physician practice',
      'Mention any prior rapid communications at conferences',
      'Highlight statistical expertise on your team',
    ],
    abstractFormat: 'Structured: Importance (why now?), Objective, Design/Setting/Participants, Interventions/Exposures, Main Outcomes and Measures, Results, Conclusions and Relevance. 350 words max.',
    website: 'jamanetwork.com',
  },
  {
    name: 'BMJ (British Medical Journal)',
    abbreviation: 'BMJ',
    publisher: 'BMJ Publishing Group',
    field: 'Medicine (Clinical)',
    impactFactor: 105.7,
    quartile: 'Q1',
    acceptanceRate: 0.07,
    turnaroundDays: 25,
    wordLimits: { abstract: 400, main: 3500, references: 50 },
    structure: ['Structured Abstract', 'Introduction', 'Methods', 'Results', 'Discussion'],
    citationStyle: 'Vancouver (numbered)',
    figureSpecs: { maxFigures: 6, format: 'EPS/TIFF/JPEG', minDPI: 300 },
    openAccess: { available: true, apc: 3365, currency: 'GBP' },
    peerReviewType: 'Open peer review (published reviews)',
    ethicsRequired: true,
    dataAvailabilityRequired: true,
    keyRequirements: [
      'Open peer review: reviewers\' names and reports published with article',
      '"What this study adds" summary box required (3 bullet points)',
      '"What is already known" box required (3 bullet points)',
      'ICMJE data sharing statement mandatory',
      'Patient or public involvement statement required',
      'Rapid response facility — all papers receive public comments',
    ],
    typicalRejectionReasons: [
      'No clear "what this study adds" beyond existing evidence',
      'Patient involvement not described or not appropriate',
      'Open peer review concerns (authors unwilling to participate)',
      'UK/European focus that limits international relevance',
    ],
    reviewerFocus: [
      '"What this study adds" — incremental advance clearly stated',
      'Patient/public involvement in study design',
      'Health equity and global applicability',
      'Transparency of methods and data',
    ],
    coverLetterTips: [
      'State explicitly: What does this add to the 3 most recent systematic reviews?',
      'Describe patient involvement in study design',
      'Note willingness for open peer review',
    ],
    abstractFormat: 'Structured with "What is already known / What this study adds" boxes. Objectives, Design, Setting, Participants, Interventions, Main outcome measures, Results, Conclusions. 400 words.',
    website: 'bmj.com',
  },
  {
    name: 'Cell',
    abbreviation: 'Cell',
    publisher: 'Elsevier (Cell Press)',
    field: 'Biology (Molecular/Cell)',
    impactFactor: 64.5,
    quartile: 'Q1',
    acceptanceRate: 0.07,
    turnaroundDays: 45,
    wordLimits: { abstract: 150, main: 8000, references: 100 },
    structure: ['Abstract', 'Introduction', 'Results', 'Discussion', 'STAR Methods', 'References'],
    citationStyle: 'Cell (author-date)',
    figureSpecs: { maxFigures: 8, format: 'EPS/PDF', minDPI: 300 },
    openAccess: { available: true, apc: 5200, currency: 'USD' },
    peerReviewType: 'Single-blind',
    ethicsRequired: true,
    dataAvailabilityRequired: true,
    keyRequirements: [
      'STAR Methods format mandatory (Structured, Transparent, Accessible, Reproducible)',
      'Key Resources Table required (reagents, antibodies, cell lines, software)',
      'Graphical Abstract (400×300px) required',
      'Highlights (4 bullet points, 85 characters each) required',
      'Data and code deposition in public repositories (e.g., GEO, GitHub)',
      'eTOC blurb (author-written lay summary) required',
    ],
    typicalRejectionReasons: [
      'Mechanism not fully elucidated — observations without mechanistic depth',
      'Single approach; multiple orthogonal validation methods needed',
      'Physiological relevance not demonstrated (only cell lines, no in vivo)',
      'Novelty insufficient relative to concurrent publications',
    ],
    reviewerFocus: [
      'Mechanistic depth — how, not just what',
      'Multiple orthogonal experimental approaches',
      'In vivo validation of in vitro findings',
      'Completeness of STAR Methods for reproducibility',
    ],
    coverLetterTips: [
      'Clearly state the conceptual advance in first sentence',
      'Describe how you validated findings using at least 3 independent approaches',
      'Address any likely concurrent submissions in the field',
    ],
    abstractFormat: 'Unstructured, 150 words. Clear problem → approach → key finding → implication. Avoid jargon; must be interpretable by all Cell Press readers.',
    website: 'cell.com/cell',
  },
  {
    name: 'Nature Medicine',
    abbreviation: 'Nat Med',
    publisher: 'Springer Nature',
    field: 'Medicine (Translational)',
    impactFactor: 82.9,
    quartile: 'Q1',
    acceptanceRate: 0.08,
    turnaroundDays: 50,
    wordLimits: { abstract: 150, main: 4000, references: 60 },
    structure: ['Abstract', 'Introduction', 'Results', 'Discussion', 'Methods'],
    citationStyle: 'Nature (numbered)',
    figureSpecs: { maxFigures: 6, format: 'PDF/EPS/TIFF', minDPI: 300 },
    openAccess: { available: true, apc: 9450, currency: 'USD' },
    peerReviewType: 'Double-blind',
    ethicsRequired: true,
    dataAvailabilityRequired: true,
    keyRequirements: [
      'Translational bridge required: bench-to-bedside or bedside-to-bench',
      'Human validation of preclinical findings strongly preferred',
      'Life Sciences Reporting Summary (LSRS) mandatory',
      'Statistics Reporting Summary mandatory',
      'Clinical trial registration required for all human interventions',
    ],
    typicalRejectionReasons: [
      'Purely clinical with no mechanistic insight',
      'Purely preclinical with no human data',
      'Missing translational relevance to human disease',
      'Underpowered clinical cohort',
    ],
    reviewerFocus: [
      'Translational significance — does this advance human medicine?',
      'Rigor of both preclinical and clinical components',
      'Biomarker validation if proposed',
      'Therapeutic target actionability',
    ],
    coverLetterTips: [
      'Lead with the unmet clinical need your work addresses',
      'Describe the translational arc: discovery → validation → clinical application',
      'Highlight any FDA-relevant findings',
    ],
    abstractFormat: 'Unstructured, 150 words. Emphasize translational bridge. State both mechanistic finding AND clinical relevance.',
    website: 'nature.com/nm',
  },
  {
    name: 'Circulation',
    abbreviation: 'Circulation',
    publisher: 'American Heart Association',
    field: 'Cardiology',
    impactFactor: 37.8,
    quartile: 'Q1',
    acceptanceRate: 0.11,
    turnaroundDays: 35,
    wordLimits: { abstract: 250, main: 4000, references: 50 },
    structure: ['Structured Abstract', 'Introduction', 'Methods', 'Results', 'Discussion', 'Supplemental Material'],
    citationStyle: 'AHA (Vancouver)',
    figureSpecs: { maxFigures: 6, format: 'EPS/TIFF', minDPI: 300 },
    openAccess: { available: true, apc: 2500, currency: 'USD' },
    peerReviewType: 'Double-blind',
    ethicsRequired: true,
    dataAvailabilityRequired: true,
    keyRequirements: [
      'Novelty and Significance statement required (2 paragraphs)',
      'AHA Scientific Statement guidelines must be followed for review articles',
      'Pre-specified statistical analysis plan required for RCTs',
      'Supplemental data encouraged for complete methods and additional analyses',
    ],
    typicalRejectionReasons: [
      'Novel finding limited to one center without validation',
      'Mechanistic studies not relevant to human cardiovascular disease',
      'Underpowered for primary endpoint',
      'Missing appropriate subgroup analyses',
    ],
    reviewerFocus: [
      'Cardiovascular clinical relevance',
      'Appropriateness of hemodynamic/imaging endpoints',
      'Adequacy of follow-up duration',
      'Consistency with existing AHA/ACC guidelines',
    ],
    coverLetterTips: [
      'State impact on AHA/ACC guideline recommendations',
      'Highlight if study addresses an area of current guideline controversy',
      'Mention any accompanying editorial you expect',
    ],
    abstractFormat: 'Structured: Background, Methods, Results, Conclusions. 250 words. Include primary endpoint with CI and p-value in Results section.',
    website: 'ahajournals.org/journal/circ',
  },
  {
    name: 'JACC (Journal of the American College of Cardiology)',
    abbreviation: 'JACC',
    publisher: 'Elsevier / ACC',
    field: 'Cardiology',
    impactFactor: 24.0,
    quartile: 'Q1',
    acceptanceRate: 0.14,
    turnaroundDays: 28,
    wordLimits: { abstract: 250, main: 3500, references: 50 },
    structure: ['Structured Abstract', 'Introduction', 'Methods', 'Results', 'Discussion', 'Perspectives'],
    citationStyle: 'JACC (Vancouver)',
    figureSpecs: { maxFigures: 8, format: 'EPS/TIFF', minDPI: 300 },
    openAccess: { available: true, apc: 2800, currency: 'USD' },
    peerReviewType: 'Double-blind',
    ethicsRequired: true,
    dataAvailabilityRequired: true,
    keyRequirements: [
      'COMPETENCY section required: list clinical competencies addressed',
      'TRANSLATIONAL OUTLOOK required for basic science papers',
      'Central illustration (single figure conveying key message) required',
      '"Perspectives" section (What is Known / What New Information this Study Contributes) required',
    ],
    typicalRejectionReasons: [
      'Missing central illustration',
      'Competency section missing or inappropriate',
      'Results not sufficiently practice-changing for cardiologists',
      'Registry data without prospective validation',
    ],
    reviewerFocus: [
      'Clinical practice impact for cardiologists',
      'Quality of central illustration',
      'Appropriate subgroup analyses',
      'Compliance with ACC/AHA reporting standards',
    ],
    coverLetterTips: [
      'Attach a draft central illustration with your cover letter',
      'Explicitly list 3 clinical competencies your paper addresses',
      'State how findings align with or challenge current ACC guidelines',
    ],
    abstractFormat: 'Structured: Background, Objectives, Methods, Results, Conclusions. 250 words. Include specific numeric results with confidence intervals.',
    website: 'jacc.org',
  },
  {
    name: 'PLOS Medicine',
    abbreviation: 'PLOS Med',
    publisher: 'PLOS',
    field: 'Medicine (General)',
    impactFactor: 15.8,
    quartile: 'Q1',
    acceptanceRate: 0.10,
    turnaroundDays: 45,
    wordLimits: { abstract: 300, main: 4000, references: 70 },
    structure: ['Abstract', 'Author Summary', 'Introduction', 'Methods', 'Results', 'Discussion'],
    citationStyle: 'Vancouver (numbered)',
    figureSpecs: { maxFigures: 8, format: 'PDF/EPS/TIFF', minDPI: 300 },
    openAccess: { available: true, apc: 3500, currency: 'USD' },
    peerReviewType: 'Single-blind',
    ethicsRequired: true,
    dataAvailabilityRequired: true,
    keyRequirements: [
      'Author Summary (150-200 words in non-technical language) mandatory',
      'All supporting data must be freely available — no exceptions',
      'Structured Abstract: Background, Methods and Findings, Conclusions',
      'Trial registration required; retrospective registration not accepted',
      'EQUATOR reporting guideline checklist required for all study types',
      'Open access — no subscription required to read',
    ],
    typicalRejectionReasons: [
      'Data not fully publicly available',
      'Author summary not accessible to lay audience',
      'Study type not appropriate for PLOS Medicine scope',
      'Incremental findings without policy or clinical implication',
    ],
    reviewerFocus: [
      'Data availability and reproducibility',
      'Adequate adjustment for potential confounders',
      'Global health relevance',
      'Clarity of Author Summary',
    ],
    coverLetterTips: [
      'Emphasize data sharing — all data must be deposited',
      'Highlight global health implications',
      'Include a draft Author Summary in the cover letter',
    ],
    abstractFormat: 'Structured: Background (context and purpose), Methods and Findings (key results with numbers), Conclusions (implications). 300 words.',
    website: 'journals.plos.org/plosmedicine',
  },
  {
    name: 'PLOS ONE',
    abbreviation: 'PLOS ONE',
    publisher: 'PLOS',
    field: 'Multidisciplinary',
    impactFactor: 3.7,
    quartile: 'Q2',
    acceptanceRate: 0.45,
    turnaroundDays: 60,
    wordLimits: { abstract: 300, main: 12000, references: 100 },
    structure: ['Abstract', 'Introduction', 'Materials and Methods', 'Results', 'Discussion'],
    citationStyle: 'Vancouver (numbered)',
    figureSpecs: { maxFigures: 20, format: 'PDF/EPS/TIFF/PNG', minDPI: 300 },
    openAccess: { available: true, apc: 1805, currency: 'USD' },
    peerReviewType: 'Single-blind',
    ethicsRequired: true,
    dataAvailabilityRequired: true,
    keyRequirements: [
      'Review criteria: scientific rigor only, NOT novelty or significance',
      'Data must be deposited in a public repository',
      'ALL raw data must be included in supplementary materials or repository',
      'EQUATOR checklist required for all study types',
      'Ethics approval statement required; IRB approval number must be stated',
    ],
    typicalRejectionReasons: [
      'Ethical concerns with study conduct',
      'Insufficient methods description for reproducibility',
      'Data not made available',
      'Statistical errors that invalidate conclusions',
    ],
    reviewerFocus: [
      'Scientific soundness and methods rigor',
      'Ethics compliance',
      'Data availability',
      'Reproducibility of methods',
    ],
    coverLetterTips: [
      'PLOS ONE does not assess novelty — focus cover letter on rigor',
      'Confirm all data are deposited or will be at acceptance',
      'List all ethical approvals obtained',
    ],
    abstractFormat: 'Structured: Background, Methodology/Principal Findings, Conclusions/Significance. 300 words. No novelty claims needed.',
    website: 'journals.plos.org/plosone',
  },
  {
    name: 'Brain',
    abbreviation: 'Brain',
    publisher: 'Oxford University Press',
    field: 'Neurology/Neuroscience',
    impactFactor: 14.5,
    quartile: 'Q1',
    acceptanceRate: 0.15,
    turnaroundDays: 40,
    wordLimits: { abstract: 200, main: 5000, references: 60 },
    structure: ['Abstract', 'Introduction', 'Materials and Methods', 'Results', 'Discussion'],
    citationStyle: 'Oxford (author-year)',
    figureSpecs: { maxFigures: 8, format: 'EPS/TIFF', minDPI: 300 },
    openAccess: { available: true, apc: 3900, currency: 'USD' },
    peerReviewType: 'Double-blind',
    ethicsRequired: true,
    dataAvailabilityRequired: true,
    keyRequirements: [
      'UK Medical Research Council and Wellcome Trust acknowledge OA policy',
      'MRI data: acquisition parameters must be fully specified',
      'Electrophysiology: exact stimulation parameters required',
      'Patient cohorts: consecutive recruitment preferred; selection criteria explicit',
    ],
    typicalRejectionReasons: [
      'Neuroimaging study without behavioral/clinical correlate',
      'Small patient cohort without power justification',
      'Missing comparison to age-matched healthy controls',
      'Insufficient localization of lesion/activation',
    ],
    reviewerFocus: [
      'Neuroanatomical precision',
      'Adequacy of control conditions',
      'Patient cohort characterization',
      'Mechanism relevance to human disease',
    ],
    coverLetterTips: [
      'State which neurological condition this advances understanding of',
      'Describe patient cohort size and recruitment method',
      'Highlight any multi-site validation',
    ],
    abstractFormat: 'Unstructured, 200 words. Cover: question, patients/subjects, methods, results (numbers), conclusion.',
    website: 'academic.oup.com/brain',
  },
  {
    name: 'Gut',
    abbreviation: 'Gut',
    publisher: 'BMJ Publishing / BSG',
    field: 'Gastroenterology',
    impactFactor: 24.5,
    quartile: 'Q1',
    acceptanceRate: 0.12,
    turnaroundDays: 35,
    wordLimits: { abstract: 250, main: 4000, references: 50 },
    structure: ['Structured Abstract', 'Introduction', 'Methods', 'Results', 'Discussion'],
    citationStyle: 'Vancouver',
    figureSpecs: { maxFigures: 6, format: 'EPS/TIFF', minDPI: 300 },
    openAccess: { available: true, apc: 2600, currency: 'GBP' },
    peerReviewType: 'Single-blind',
    ethicsRequired: true,
    dataAvailabilityRequired: true,
    keyRequirements: [
      'Lay Summary (100 words) required for all papers',
      'Endoscopy videos encouraged for procedural studies',
      'Microbiome studies: MIMARKS/MIxS reporting standards required',
      'Histopathology: standardized scoring system must be referenced',
    ],
    typicalRejectionReasons: [
      'Mouse-only data for a clinical gastroenterology question',
      'Single-center endoscopy study without validation',
      'Microbiome study without appropriate controls',
    ],
    reviewerFocus: [
      'GI-specific clinical relevance',
      'Mucosal immunology rigor',
      'Microbiome methodology quality',
      'Translational applicability',
    ],
    coverLetterTips: [
      'Frame findings in terms of GI disease burden',
      'Include any endoscopy images or videos available',
    ],
    abstractFormat: 'Structured: Objective, Design, Results, Conclusions. 250 words. Include specific quantitative results.',
    website: 'gut.bmj.com',
  },
  {
    name: 'Journal of Clinical Oncology',
    abbreviation: 'JCO',
    publisher: 'ASCO',
    field: 'Oncology',
    impactFactor: 50.7,
    quartile: 'Q1',
    acceptanceRate: 0.10,
    turnaroundDays: 30,
    wordLimits: { abstract: 300, main: 4500, references: 60 },
    structure: ['Abstract', 'Introduction', 'Patients and Methods', 'Results', 'Discussion'],
    citationStyle: 'JCO (Vancouver)',
    figureSpecs: { maxFigures: 6, format: 'EPS/TIFF', minDPI: 300 },
    openAccess: { available: true, apc: 3600, currency: 'USD' },
    peerReviewType: 'Double-blind',
    ethicsRequired: true,
    dataAvailabilityRequired: true,
    keyRequirements: [
      '"Patients and Methods" section (not just Methods)',
      'ASCO Conflict of Interest disclosure policy applies to all authors',
      'Kaplan-Meier curves required for all survival analyses',
      'CONSORT diagram mandatory for all phase II-III trials',
      'All trials must be registered in ClinicalTrials.gov prior to enrollment',
      'Response criteria (RECIST, etc.) must be specified',
    ],
    typicalRejectionReasons: [
      'Phase I dose-escalation without efficacy signal',
      'Non-validated surrogate endpoint used as primary outcome',
      'Missing hazard ratios and confidence intervals',
      'Historical control comparison without appropriate justification',
    ],
    reviewerFocus: [
      'Clinical trial design rigor',
      'Appropriateness of endpoints (OS vs. PFS)',
      'Toxicity reporting completeness',
      'Patient population generalizability',
    ],
    coverLetterTips: [
      'State the phase and primary endpoint of your trial upfront',
      'Describe how your results affect treatment decision-making',
      'Note any oral presentation at ASCO Annual Meeting if applicable',
    ],
    abstractFormat: 'Structured: Purpose, Patients and Methods, Results, Conclusion. 300 words. Include hazard ratios and 95% CIs for survival outcomes.',
    website: 'ascopubs.org/journal/jco',
  },
  {
    name: 'Annals of Internal Medicine',
    abbreviation: 'Ann Intern Med',
    publisher: 'American College of Physicians',
    field: 'Internal Medicine',
    impactFactor: 39.2,
    quartile: 'Q1',
    acceptanceRate: 0.07,
    turnaroundDays: 28,
    wordLimits: { abstract: 250, main: 3500, references: 60 },
    structure: ['Structured Abstract', 'Introduction', 'Methods', 'Results', 'Discussion', 'Conclusion'],
    citationStyle: 'ACP (Vancouver)',
    figureSpecs: { maxFigures: 4, format: 'EPS/TIFF', minDPI: 300 },
    openAccess: { available: false },
    peerReviewType: 'Double-blind',
    ethicsRequired: true,
    dataAvailabilityRequired: true,
    keyRequirements: [
      'Mandatory Conclusion section (distinct from Discussion)',
      'Key summary: "What the paper adds to current knowledge" required',
      'Systematic reviews require PRISMA checklist',
      'Uniform Requirements for Manuscripts (ICMJE) applied strictly',
      'Clinical significance of findings must be explicitly addressed',
    ],
    typicalRejectionReasons: [
      'Conclusions not supported by study design',
      'Single-center study for a common clinical condition',
      'No pre-specified primary outcome',
      'Missing clinical significance discussion',
    ],
    reviewerFocus: [
      'Internal medicine clinical relevance',
      'Appropriateness of design for question',
      'Accuracy of conclusions relative to data strength',
      'Patient-centered outcomes',
    ],
    coverLetterTips: [
      'State impact on general internists, not subspecialists',
      'Highlight any practice-changing implications clearly',
      'Confirm pre-registration if applicable',
    ],
    abstractFormat: 'Structured: Background, Objective, Design, Setting, Patients, Intervention, Measurements, Results, Limitation, Conclusion. 250 words.',
    website: 'annals.org',
  },
  {
    name: 'eLife',
    abbreviation: 'eLife',
    publisher: 'eLife Sciences Publications',
    field: 'Life Sciences / Biomedical',
    impactFactor: 7.7,
    quartile: 'Q1',
    acceptanceRate: 0.15,
    turnaroundDays: 70,
    wordLimits: { abstract: 150, main: 8000, references: 100 },
    structure: ['Abstract', 'eLife Digest', 'Introduction', 'Results', 'Discussion', 'Materials and Methods'],
    citationStyle: 'APA (author-date)',
    figureSpecs: { maxFigures: 12, format: 'EPS/PDF/TIFF', minDPI: 300 },
    openAccess: { available: true, apc: 0, currency: 'USD' },
    peerReviewType: 'Consulted (reviewers consulted before decision)',
    ethicsRequired: true,
    dataAvailabilityRequired: true,
    keyRequirements: [
      'No APC for articles submitted after 2023 (changed to publishing model)',
      'eLife Digest (lay summary, 400 words) required at acceptance',
      'Preprint must be posted on bioRxiv/medRxiv prior to submission (preferred)',
      'Decision Letter and Author Response are published openly',
      'Revised Decision Letters also published — full transparency',
    ],
    typicalRejectionReasons: [
      'Missing mechanistic insight despite interesting observations',
      'Lack of in vivo validation',
      'Insufficient methodological detail in a computational study',
    ],
    reviewerFocus: [
      'Technical rigor and reproducibility',
      'Mechanistic depth',
      'Open science compliance',
      'Quality of public data deposition',
    ],
    coverLetterTips: [
      'Link your bioRxiv preprint',
      'State which eLife editor is most appropriate',
      'Note your commitment to posting reviewer correspondence publicly',
    ],
    abstractFormat: 'Unstructured, 150 words. Written for all life scientists. Avoid field-specific jargon.',
    website: 'elifesciences.org',
  },
  {
    name: 'JAMA Internal Medicine',
    abbreviation: 'JAMA Intern Med',
    publisher: 'AMA',
    field: 'Internal Medicine',
    impactFactor: 39.9,
    quartile: 'Q1',
    acceptanceRate: 0.08,
    turnaroundDays: 28,
    wordLimits: { abstract: 250, main: 3500, references: 50 },
    structure: ['Structured Abstract', 'Introduction', 'Methods', 'Results', 'Discussion', 'Conclusions'],
    citationStyle: 'AMA style',
    figureSpecs: { maxFigures: 4, format: 'EPS/TIFF', minDPI: 300 },
    openAccess: { available: true, apc: 3000, currency: 'USD' },
    peerReviewType: 'Double-blind',
    ethicsRequired: true,
    dataAvailabilityRequired: true,
    keyRequirements: [
      'Viewpoint and Research Letter formats available for shorter communications',
      'Emphasis on reducing overdiagnosis, overtreatment, and medical reversal',
      'Health policy implications highlighted where possible',
      'AMA Manual of Style 11th edition required',
    ],
    typicalRejectionReasons: [
      'Findings support further treatment rather than questioning current practice',
      'Insufficient patient-centered outcomes',
      'Industry-funded with potential conflicts',
    ],
    reviewerFocus: [
      'Less is more medicine: does this support judicious use?',
      'Patient-centered outcomes',
      'Cost-effectiveness when relevant',
      'Independent from industry influence',
    ],
    coverLetterTips: [
      'Frame findings in terms of avoiding harm from overtreatment',
      'State funding sources clearly upfront',
      'Highlight if results challenge a widely-used treatment',
    ],
    abstractFormat: 'Structured with Importance, Objective, Design/Setting/Participants, Interventions, Main Outcomes and Measures, Results, Conclusions and Relevance.',
    website: 'jamanetwork.com/journals/jamainternalmedicine',
  },
  {
    name: 'Diabetes Care',
    abbreviation: 'Diabetes Care',
    publisher: 'ADA',
    field: 'Endocrinology / Diabetes',
    impactFactor: 16.2,
    quartile: 'Q1',
    acceptanceRate: 0.16,
    turnaroundDays: 35,
    wordLimits: { abstract: 250, main: 4500, references: 60 },
    structure: ['Abstract', 'Introduction', 'Research Design and Methods', 'Results', 'Discussion'],
    citationStyle: 'ADA (author-year + numbered)',
    figureSpecs: { maxFigures: 6, format: 'EPS/TIFF', minDPI: 300 },
    openAccess: { available: true, apc: 2500, currency: 'USD' },
    peerReviewType: 'Double-blind',
    ethicsRequired: true,
    dataAvailabilityRequired: false,
    keyRequirements: [
      '"Research Design and Methods" — not just "Methods"',
      'Metabolic control: HbA1c, FPG must be reported in both mmol/mol and %',
      'ADA diagnostic criteria for diabetes classification must be referenced',
      'Insulin regimens described in full detail',
      'Hypoglycemia episodes classified using ADA consensus criteria',
    ],
    typicalRejectionReasons: [
      'Using outdated diagnostic criteria for diabetes classification',
      'Short follow-up for a glycemic intervention trial',
      'Missing HbA1c dual unit reporting',
      'Industry-sponsored trial with potential for reporting bias',
    ],
    reviewerFocus: [
      'ADA standards of care alignment',
      'Glucose measurement methodology',
      'Hypoglycemia reporting completeness',
      'Long-term cardiovascular implications',
    ],
    coverLetterTips: [
      'Cite relevant ADA Standards of Care guideline',
      'State duration of diabetes in cohort explicitly',
      'Highlight any CGM-based outcomes if applicable',
    ],
    abstractFormat: 'Structured: Objective, Research Design and Methods, Results, Conclusions. Include HbA1c values in both mmol/mol and % format.',
    website: 'care.diabetesjournals.org',
  },
  {
    name: 'Radiology',
    abbreviation: 'Radiology',
    publisher: 'RSNA',
    field: 'Radiology',
    impactFactor: 19.7,
    quartile: 'Q1',
    acceptanceRate: 0.13,
    turnaroundDays: 30,
    wordLimits: { abstract: 250, main: 3500, references: 40 },
    structure: ['Abstract', 'Introduction', 'Materials and Methods', 'Results', 'Discussion'],
    citationStyle: 'Radiology (Vancouver)',
    figureSpecs: { maxFigures: 6, format: 'TIFF/DICOM', minDPI: 600 },
    openAccess: { available: true, apc: 2450, currency: 'USD' },
    peerReviewType: 'Double-blind',
    ethicsRequired: true,
    dataAvailabilityRequired: true,
    keyRequirements: [
      'STARD checklist required for diagnostic accuracy studies',
      'Image quality grading systems must be referenced',
      'AI/radiomics studies: TRIPOD+AI checklist mandatory',
      'Scanner parameters: field strength, sequence, contrast agent dose required',
      'IRB approval and HIPAA compliance statement required',
      'Structured Summary: Key Results and Implications (for online)',
    ],
    typicalRejectionReasons: [
      'Retrospective single-center AI study without prospective validation',
      'Missing TRIPOD checklist for AI/ML studies',
      'Image quality not standardized across patients',
      'Reader blinding not described',
    ],
    reviewerFocus: [
      'Imaging protocol standardization',
      'Inter-reader reliability (kappa statistics)',
      'Appropriate reference standard for diagnostic studies',
      'Clinical impact on patient management',
    ],
    coverLetterTips: [
      'State MRI/CT scanner specifications upfront',
      'Describe blinding of image readers explicitly',
      'Include STARD/TRIPOD checklist as supplementary material',
    ],
    abstractFormat: 'Structured with Key Results (2-3 bullet points max 25 words each) plus Purpose, Materials and Methods, Results, Conclusion. 250 words total.',
    website: 'pubs.rsna.org/journal/radiology',
  },
  {
    name: 'Lancet Digital Health',
    abbreviation: 'Lancet Digit Health',
    publisher: 'Elsevier',
    field: 'Digital Health / Health Informatics',
    impactFactor: 36.6,
    quartile: 'Q1',
    acceptanceRate: 0.10,
    turnaroundDays: 40,
    wordLimits: { abstract: 250, main: 4500, references: 60 },
    structure: ['Abstract', 'Introduction', 'Methods', 'Results', 'Discussion'],
    citationStyle: 'Lancet (Vancouver)',
    figureSpecs: { maxFigures: 6, format: 'EPS/PDF', minDPI: 300 },
    openAccess: { available: true, apc: 6400, currency: 'USD' },
    peerReviewType: 'Double-blind',
    ethicsRequired: true,
    dataAvailabilityRequired: true,
    keyRequirements: [
      'TRIPOD-AI checklist mandatory for all AI/ML studies',
      'Code availability required (GitHub link)',
      'Model performance must include both discrimination AND calibration',
      'External validation cohort required for diagnostic/prognostic models',
      'CONSORT-AI extension required for AI clinical trials',
    ],
    typicalRejectionReasons: [
      'Single-center AI model without external validation',
      'Only AUC reported — missing calibration, sensitivity, specificity',
      'No code deposited publicly',
      'Algorithm "black box" with no explainability analysis',
    ],
    reviewerFocus: [
      'External validation of AI models',
      'Clinical implementation feasibility',
      'Algorithmic fairness across demographic groups',
      'Reproducibility via code sharing',
    ],
    coverLetterTips: [
      'Provide GitHub/Zenodo link for model code',
      'State which demographic subgroups were analyzed for equity',
      'Describe the clinical deployment context',
    ],
    abstractFormat: 'Structured: Background, Methods, Findings, Interpretation, Funding. 250 words. Report AUROC/AUPRC with 95% CI, calibration measure, and external validation results.',
    website: 'thelancet.com/journals/landig',
  },
  {
    name: 'JMIR (Journal of Medical Internet Research)',
    abbreviation: 'JMIR',
    publisher: 'JMIR Publications',
    field: 'Health Informatics / Digital Health',
    impactFactor: 7.4,
    quartile: 'Q1',
    acceptanceRate: 0.30,
    turnaroundDays: 60,
    wordLimits: { abstract: 300, main: 8000, references: 80 },
    structure: ['Abstract', 'Introduction', 'Methods', 'Results', 'Discussion', 'Conclusions'],
    citationStyle: 'APA / Vancouver hybrid',
    figureSpecs: { maxFigures: 15, format: 'PNG/JPEG/PDF', minDPI: 150 },
    openAccess: { available: true, apc: 2500, currency: 'USD' },
    peerReviewType: 'Single-blind',
    ethicsRequired: true,
    dataAvailabilityRequired: true,
    keyRequirements: [
      'CHERRIES checklist required for online survey studies',
      'Mobile health app studies: MARS (Mobile App Rating Scale) should be cited',
      'Usability studies: System Usability Scale (SUS) preferred',
      'Structured abstract: Background, Objective, Methods, Results, Conclusions, Keywords',
      'Multimedia appendix (video, app screenshots) encouraged',
    ],
    typicalRejectionReasons: [
      'App evaluation without clinical outcome measurement',
      'Survey study with response rate <30% without bias analysis',
      'Missing usability validation before clinical deployment',
    ],
    reviewerFocus: [
      'User engagement metrics quality',
      'Clinical outcome linkage for app studies',
      'Survey methodology rigor',
      'Technology feasibility in real-world settings',
    ],
    coverLetterTips: [
      'Provide screenshots of the app or platform',
      'State response rate and non-response bias analysis',
      'Describe the technical implementation clearly',
    ],
    abstractFormat: 'Structured with separate sections: Background, Objective, Methods, Results, Conclusions. End with 3-5 keywords not in title. 300 words.',
    website: 'jmir.org',
  },
  {
    name: 'American Journal of Epidemiology',
    abbreviation: 'Am J Epidemiol',
    publisher: 'Oxford University Press',
    field: 'Epidemiology',
    impactFactor: 5.5,
    quartile: 'Q1',
    acceptanceRate: 0.18,
    turnaroundDays: 60,
    wordLimits: { abstract: 250, main: 5000, references: 60 },
    structure: ['Abstract', 'Introduction', 'Methods', 'Results', 'Discussion'],
    citationStyle: 'AJE (numbered)',
    figureSpecs: { maxFigures: 6, format: 'EPS/TIFF', minDPI: 300 },
    openAccess: { available: true, apc: 3800, currency: 'USD' },
    peerReviewType: 'Double-blind',
    ethicsRequired: true,
    dataAvailabilityRequired: false,
    keyRequirements: [
      'STROBE checklist mandatory for all observational studies',
      'DAG (Directed Acyclic Graph) for confounding structure strongly encouraged',
      'Missing data: multiple imputation approach required if >5% missing',
      'Sensitivity analyses must be pre-specified in Methods',
      'E-value required for observational studies to address unmeasured confounding',
    ],
    typicalRejectionReasons: [
      'Missing STROBE checklist',
      'No DAG to justify confounder selection',
      'E-value not calculated for key confounders',
      'Cross-sectional design for a clearly temporally dependent question',
    ],
    reviewerFocus: [
      'Causal inference methodology',
      'Confounding control rigor',
      'Selection and information bias assessment',
      'E-value and sensitivity analyses',
    ],
    coverLetterTips: [
      'Attach STROBE checklist as required document',
      'Include a DAG in the paper or supplementary',
      'State all sensitivity analyses planned a priori',
    ],
    abstractFormat: 'Unstructured preferred. 250 words. Must include: study design, population, exposure, outcome, key result with confidence interval, and limitation.',
    website: 'academic.oup.com/aje',
  },
  {
    name: 'npj Digital Medicine',
    abbreviation: 'npj Digit Med',
    publisher: 'Springer Nature',
    field: 'Digital Medicine',
    impactFactor: 15.2,
    quartile: 'Q1',
    acceptanceRate: 0.15,
    turnaroundDays: 45,
    wordLimits: { abstract: 200, main: 4000, references: 60 },
    structure: ['Abstract', 'Introduction', 'Methods', 'Results', 'Discussion'],
    citationStyle: 'Nature (numbered)',
    figureSpecs: { maxFigures: 8, format: 'PDF/EPS/TIFF', minDPI: 300 },
    openAccess: { available: true, apc: 4290, currency: 'USD' },
    peerReviewType: 'Double-blind',
    ethicsRequired: true,
    dataAvailabilityRequired: true,
    keyRequirements: [
      'TRIPOD-AI or CONSORT-AI checklist based on study type',
      'Model code must be made available',
      'Prospective validation preferred over retrospective',
      'Diversity and equity analysis in model performance required',
    ],
    typicalRejectionReasons: [
      'Retrospective single-site AI study',
      'No demographic breakdown of model performance',
      'Code not available',
    ],
    reviewerFocus: [
      'Prospective design and real-world validation',
      'Demographic equity in model performance',
      'Clinical workflow integration',
    ],
    coverLetterTips: [
      'Describe the clinical deployment pathway',
      'State model fairness analysis methods',
    ],
    abstractFormat: 'Unstructured, 200 words. Key finding and clinical implication must be in final sentence.',
    website: 'nature.com/npjdigitalmed',
  },
  {
    name: 'Cochrane Database of Systematic Reviews',
    abbreviation: 'Cochrane DB Syst Rev',
    publisher: 'Wiley / Cochrane',
    field: 'Systematic Reviews / Evidence Synthesis',
    impactFactor: 11.9,
    quartile: 'Q1',
    acceptanceRate: 0.50,
    turnaroundDays: 180,
    wordLimits: { abstract: 400, main: 50000, references: 500 },
    structure: ['Abstract', 'Plain Language Summary', 'Background', 'Objectives', 'Methods', 'Results', 'Discussion', "Authors' Conclusions"],
    citationStyle: 'Vancouver',
    figureSpecs: { maxFigures: 50, format: 'Any', minDPI: 150 },
    openAccess: { available: true, apc: 0, currency: 'USD' },
    peerReviewType: 'Cochrane editorial process',
    ethicsRequired: false,
    dataAvailabilityRequired: true,
    keyRequirements: [
      'MUST be registered in PROSPERO before submission',
      'Protocol must be published in Cochrane before full review',
      'RevMan 5 or RevMan Web software required for meta-analysis',
      'GRADE approach mandatory for all outcome assessments',
      'Funnel plot asymmetry assessed if ≥10 studies',
      'Plain Language Summary mandatory (non-technical, 200 words)',
      'Cochrane Handbook methodology must be followed precisely',
    ],
    typicalRejectionReasons: [
      'Protocol not registered before search',
      'Cochrane Handbook methods not followed',
      'GRADE assessment missing or incorrect',
      'RevMan not used for analysis',
    ],
    reviewerFocus: [
      'Adherence to Cochrane Handbook 6.0',
      'Completeness of search strategy',
      'GRADE quality of evidence for each outcome',
      'Risk of Bias 2 assessment correctness',
    ],
    coverLetterTips: [
      'Include PROSPERO registration number',
      'Confirm protocol is published and link it',
      'State your Cochrane review group affiliation',
    ],
    abstractFormat: 'Structured Cochrane format: Background, Objectives, Search Methods, Selection Criteria, Data Collection and Analysis, Main Results, Authors\' Conclusions. 400 words.',
    website: 'cochranelibrary.com',
  },
];

export function searchJournals(query: string): JournalRequirements[] {
  const q = query.toLowerCase();
  return JOURNAL_DATABASE.filter(j =>
    j.name.toLowerCase().includes(q) ||
    j.abbreviation.toLowerCase().includes(q) ||
    j.field.toLowerCase().includes(q) ||
    j.publisher.toLowerCase().includes(q)
  );
}

export function getJournalByField(field: string): JournalRequirements[] {
  const q = field.toLowerCase();
  return JOURNAL_DATABASE.filter(j => j.field.toLowerCase().includes(q));
}

export function getJournalsByQuartile(quartile: 'Q1' | 'Q2' | 'Q3' | 'Q4'): JournalRequirements[] {
  return JOURNAL_DATABASE.filter(j => j.quartile === quartile);
}
