export interface StudyType {
  id: string;
  name: string;
  category: 'primary' | 'secondary' | 'qualitative' | 'mixed' | 'other';
  definition: string;
  whenToUse: string[];
  whenNotToUse: string[];
  framework: string;
  reportingGuideline: string;
  reportingGuidelineUrl: string;
  keySteps: { step: number; title: string; description: string }[];
  commonMistakes: { mistake: string; consequence: string; fix: string }[];
  sampleSizeConsiderations: string;
  statisticalApproach: string;
  howToWriteEachSection: { section: string; guidance: string }[];
  exampleResearchQuestions: string[];
  strengthsAndLimitations: { strengths: string[]; limitations: string[] };
  evidence_level: string;
  timeRequired: string;
  cost: 'Low' | 'Medium' | 'High' | 'Low to Medium' | 'Medium to High';
  color: string;
}

export const STUDY_TYPES: StudyType[] = [
  {
    id: 'systematic-review',
    name: 'Systematic Review',
    category: 'secondary',
    definition: 'A structured, comprehensive review of all available evidence on a specific question, using explicit and reproducible methods to identify, select, critically appraise, and synthesize studies.',
    whenToUse: [
      'Summarizing evidence to inform clinical practice or policy',
      'Before conducting a primary study (to confirm a gap exists)',
      'When multiple small studies have been conducted on the same question',
      'For health technology assessments and guideline development',
    ],
    whenNotToUse: [
      'When the primary literature is too heterogeneous for synthesis',
      'When you want to explore a broad topic area (use scoping review)',
      'When the field is too new and few primary studies exist',
    ],
    framework: 'PICO (Population, Intervention, Comparison, Outcome) or PICOS (+ Study design)',
    reportingGuideline: 'PRISMA 2020',
    reportingGuidelineUrl: 'prisma-statement.org',
    keySteps: [
      { step: 1, title: 'Register protocol', description: 'Register in PROSPERO before starting the search. Define all eligibility criteria, outcomes, and analysis methods in advance.' },
      { step: 2, title: 'Develop search strategy', description: 'Create comprehensive Boolean search strings for ≥2 databases. Use MeSH terms for PubMed. Have a librarian peer-review your search.' },
      { step: 3, title: 'Screen titles/abstracts', description: 'Two independent reviewers screen using Rayyan or Covidence. Resolve conflicts by consensus or third reviewer.' },
      { step: 4, title: 'Retrieve and screen full texts', description: 'Two reviewers independently assess full texts against pre-specified eligibility criteria. Document reasons for exclusion.' },
      { step: 5, title: 'Extract data', description: 'Use a standardized extraction form. Extract in duplicate. Pilot the form on 5 papers before full extraction.' },
      { step: 6, title: 'Assess risk of bias', description: 'Use RoB 2 for RCTs, ROBINS-I for non-randomized studies, QUADAS-2 for diagnostic studies.' },
      { step: 7, title: 'Synthesize results', description: 'If studies are sufficiently homogeneous, conduct meta-analysis. Otherwise, narrative synthesis using SWiM framework.' },
      { step: 8, title: 'GRADE the evidence', description: 'Apply GRADE approach to each outcome: assess certainty as high/moderate/low/very low.' },
      { step: 9, title: 'Write and report', description: 'Follow PRISMA 2020 checklist (27 items). Include PRISMA flow diagram with numbers at each stage.' },
    ],
    commonMistakes: [
      { mistake: 'Searching only 1-2 databases', consequence: 'Missing up to 50% of eligible studies, biasing conclusions', fix: 'Search minimum 3 databases + grey literature + trial registries' },
      { mistake: 'Post-hoc registration in PROSPERO', consequence: 'Allows outcome reporting bias; most journals now reject', fix: 'Register before any screening begins' },
      { mistake: 'Single reviewer screening', consequence: 'Up to 10-15% of eligible studies missed', fix: 'Always use two independent reviewers with conflict resolution process' },
      { mistake: 'Not assessing risk of bias', consequence: 'Cannot interpret reliability of pooled estimates', fix: 'Use validated tools: RoB 2, ROBINS-I, QUADAS-2' },
      { mistake: 'Ignoring heterogeneity (I²)', consequence: 'Meta-analysis of incompatible studies produces misleading pooled estimate', fix: 'If I²>75%, do subgroup analyses or narrative synthesis instead' },
      { mistake: 'Combining all study designs in one meta-analysis', consequence: 'Methodological heterogeneity inflates apparent precision', fix: 'Stratify analyses by study design' },
    ],
    sampleSizeConsiderations: 'No fixed minimum. Adequacy depends on question specificity. Broad topics may yield 100+ studies; narrow interventions may have only 3-5. Power calculation for meta-analysis: minimum 10 studies per meta-regression covariate.',
    statisticalApproach: 'Random-effects model (DerSimonian-Laird) preferred when heterogeneity expected. Report I², tau², Cochran Q. For rare outcomes: Peto or Mantel-Haenszel. For continuous outcomes: standardized mean difference (SMD) or mean difference (MD). Assess publication bias with Egger\'s test if ≥10 studies.',
    howToWriteEachSection: [
      { section: 'Abstract', guidance: 'Background: 1 sentence why this matters. Objectives: 1 PICO question. Methods: databases, dates, design filter. Results: n studies, n participants, key pooled estimate with CI. Conclusions: clinical implication + certainty of evidence.' },
      { section: 'Introduction', guidance: '3 paragraphs: (1) Clinical burden of the condition. (2) Current evidence gap. (3) Objectives of this review. End with: "We conducted a systematic review to [PICO question]."' },
      { section: 'Methods', guidance: 'Follow PRISMA 2020 item by item. Include: protocol registration number, eligibility criteria, information sources with dates, search strategy verbatim, selection process, data collection, outcomes, risk of bias tool, synthesis methods, certainty assessment.' },
      { section: 'Results', guidance: 'Start with PRISMA flow numbers. Then study characteristics table. Then risk of bias summary. Then outcome-by-outcome results. Forest plots for each meta-analysis. End with GRADE summary of findings table.' },
      { section: 'Discussion', guidance: 'Para 1: Summary of main findings in plain language. Para 2: Comparison with existing reviews. Para 3: Strengths of this review. Para 4: Limitations (bias, heterogeneity, publication bias). Para 5: Implications for practice and research.' },
    ],
    exampleResearchQuestions: [
      'What is the efficacy of SSRIs vs. placebo for major depressive disorder in adults?',
      'What are the risk factors for cardiovascular disease in patients with type 2 diabetes?',
      'What is the diagnostic accuracy of point-of-care troponin for NSTEMI?',
    ],
    strengthsAndLimitations: {
      strengths: ['Highest evidence level for clinical questions', 'Reproducible and transparent', 'Can detect effects not visible in individual studies', 'Reduces publication bias when done correctly'],
      limitations: ['Time-consuming (6-24 months)', 'Dependent on quality of primary studies', 'Cannot overcome GIGO (garbage in, garbage out)', 'Heterogeneity may prevent pooling'],
    },
    evidence_level: 'Level I (Highest)',
    timeRequired: '6-18 months',
    cost: 'Medium',
    color: '#2d6be4',
  },
  {
    id: 'scoping-review',
    name: 'Scoping Review',
    category: 'secondary',
    definition: 'A type of knowledge synthesis that systematically maps the extent, range, and nature of evidence on a topic, without appraising study quality or synthesizing findings statistically. Goal is breadth, not depth.',
    whenToUse: [
      'Mapping the breadth of available evidence on an emerging topic',
      'Clarifying key concepts, definitions, or terminology in a field',
      'Identifying gaps in evidence to inform future systematic reviews',
      'When the literature is too heterogeneous for systematic review',
      'When inclusion of diverse study designs is needed',
      'Describing types of evidence and their characteristics',
    ],
    whenNotToUse: [
      'When you need to answer a specific clinical question (use systematic review)',
      'When a quality assessment of included studies is required',
      'When a quantitative pooled estimate is the goal',
    ],
    framework: 'PCC (Population, Concept, Context) — NOT PICO',
    reportingGuideline: 'PRISMA-ScR (PRISMA extension for Scoping Reviews)',
    reportingGuidelineUrl: 'prisma-statement.org/scoping',
    keySteps: [
      { step: 1, title: 'Define research question using PCC', description: 'P: Who is the population? C: What is the main concept? C: What is the context (setting, geography, time)? Scoping reviews use PCC, not PICO.' },
      { step: 2, title: 'Register protocol', description: 'Register in OSF or PROSPERO (now accepts scoping reviews). Publish protocol if possible.' },
      { step: 3, title: 'Develop search strategy', description: 'Broader search than systematic review. Search all relevant databases + grey literature + websites. No study design filter.' },
      { step: 4, title: 'Screen in duplicate', description: 'Two reviewers screen titles/abstracts then full texts. No quality assessment at this stage.' },
      { step: 5, title: 'Chart the data', description: 'Extract data using a charting form (not "data extraction"). Capture: study characteristics, setting, population, key findings related to the concept.' },
      { step: 6, title: 'Collate and summarize', description: 'Describe what types of evidence exist, from where, on what populations, about what aspects of the concept. Use frequency counts, maps, tables.' },
      { step: 7, title: 'Optional: Consultation', description: 'Engage stakeholders (patients, clinicians, policymakers) to validate findings and identify additional sources.' },
      { step: 8, title: 'Report using PRISMA-ScR', description: 'Follow all 20 PRISMA-ScR items. Include flow diagram. Note: do NOT include GRADE or quality assessment.' },
    ],
    commonMistakes: [
      { mistake: 'Using PICO instead of PCC framework', consequence: 'Narrows the question inappropriately; misrepresents scoping intent', fix: 'Use Population, Concept, Context for all scoping reviews' },
      { mistake: 'Including quality assessment of studies', consequence: 'Conflates scoping with systematic review; methodologically inappropriate', fix: 'Do NOT appraise quality in a scoping review — this is by design' },
      { mistake: 'Drawing conclusions about "best" evidence or recommendations', consequence: 'Overstates what scoping reviews can conclude', fix: 'Conclude only about the nature, extent, and distribution of evidence' },
      { mistake: 'Using PRISMA instead of PRISMA-ScR', consequence: 'Incomplete reporting; checklist rejection by reviewers', fix: 'Always use the 20-item PRISMA-ScR extension' },
      { mistake: 'Searching too few databases', consequence: 'Misses key conceptual literature', fix: 'Search broadly: academic databases + grey literature + websites + unpublished theses' },
    ],
    sampleSizeConsiderations: 'No minimum; defined by saturation of concepts, not statistical power. A scoping review may include 20 studies or 2000 depending on the breadth of the topic.',
    statisticalApproach: 'Descriptive statistics only: frequency counts, percentages, ranges. NO meta-analysis, NO pooled estimates, NO effect sizes. Use tables, maps, and diagrams to display patterns.',
    howToWriteEachSection: [
      { section: 'Introduction', guidance: 'State the concept being mapped. Explain why mapping is needed (heterogeneity, emerging field, definitional confusion). State PCC framework explicitly. End with aim: "to map the extent and nature of evidence on [concept]."' },
      { section: 'Methods', guidance: 'State PCC elements. List databases, grey literature sources, dates. Provide verbatim search string. Describe screening process (2 reviewers). Describe charting form. Note: explicitly state that quality assessment was not performed and explain why.' },
      { section: 'Results', guidance: 'PRISMA-ScR flow diagram first. Then: characteristics of included sources (table: author, year, country, design, population, concept focus). Then narrative summary of what was found, organized thematically.' },
      { section: 'Discussion', guidance: 'Summarize patterns in the evidence. What types of studies exist? What populations? What concepts are well-studied vs. gaps? Implications for future systematic reviews. Limitations of the scoping review.' },
    ],
    exampleResearchQuestions: [
      'What evidence exists on the use of AI in primary care? (PCC: adults in primary care, AI clinical applications, primary care settings globally)',
      'How has "resilience" been conceptualized and measured in cancer survivors?',
      'What types of interventions have been studied for social isolation in older adults?',
    ],
    strengthsAndLimitations: {
      strengths: ['Captures breadth across heterogeneous literature', 'No study design exclusion', 'Maps gaps for future research', 'Faster than systematic review'],
      limitations: ['Cannot assess quality of evidence', 'Cannot make clinical recommendations', 'May miss depth by prioritizing breadth', 'Terminology not yet standardized globally'],
    },
    evidence_level: 'Evidence map (not clinical evidence level)',
    timeRequired: '3-12 months',
    cost: 'Medium',
    color: '#0d9e6e',
  },
  {
    id: 'narrative-review',
    name: 'Narrative Review',
    category: 'secondary',
    definition: 'A qualitative synthesis that provides an overview and critical discussion of existing literature on a topic. Unlike systematic reviews, the search and selection methods are not necessarily explicit or reproducible.',
    whenToUse: [
      'Providing a broad educational overview for clinicians',
      'Discussing a complex clinical or scientific topic comprehensively',
      'Identifying controversies and areas of debate in a field',
      'When a systematic approach is not feasible or appropriate',
      'Invited reviews for journals seeking expert perspectives',
    ],
    whenNotToUse: [
      'When a specific clinical question needs an evidence-based answer',
      'When you need to claim systematic or complete coverage',
      'As justification for clinical guidelines (use systematic review)',
    ],
    framework: 'Flexible — typically based on key themes or chronology',
    reportingGuideline: 'SANRA (Scale for Assessment of Narrative Review Articles)',
    reportingGuidelineUrl: 'equator-network.org/reporting-guidelines/sanra',
    keySteps: [
      { step: 1, title: 'Define scope and audience', description: 'Clearly define what aspects of the topic you will cover. Identify target reader. Narrow or broad scope decision.' },
      { step: 2, title: 'Search literature', description: 'No formal search protocol required, but document which databases and terms you used. Aim for comprehensive coverage of key papers.' },
      { step: 3, title: 'Organize by themes', description: 'Group literature into logical thematic sections. Use a conceptual framework or chronological approach.' },
      { step: 4, title: 'Write critically', description: 'Do not just summarize papers — critically appraise them. Compare conflicting findings. Draw your own interpretive conclusions.' },
      { step: 5, title: 'Apply SANRA criteria', description: 'Self-assess against 6 SANRA criteria: justification of review importance, literature search, referencing, scientific reasoning, appropriate writing.' },
    ],
    commonMistakes: [
      { mistake: 'Summarizing papers without critical appraisal', consequence: 'Becomes annotated bibliography, not a review — rejected by most journals', fix: 'Compare, contrast, and synthesize findings. Take a position.' },
      { mistake: 'Not describing search methods at all', consequence: 'Fails SANRA criterion 2; suggests selection bias', fix: 'Describe your search approach even if informal' },
      { mistake: 'Citing only supportive papers (confirmation bias)', consequence: 'Presents unbalanced view; undermines credibility', fix: 'Actively seek contradictory evidence and address it' },
      { mistake: 'No conclusions or implications', consequence: 'Leaves reader without guidance; rejected as not adding value', fix: 'End with clear synthesis: what we know, what we don\'t, what should happen next' },
    ],
    sampleSizeConsiderations: 'Not applicable in the same way as primary studies. Typically cite 50-150+ references depending on topic breadth and journal requirements.',
    statisticalApproach: 'No primary statistical analysis. May report statistics from cited studies. Tables summarizing key study findings are useful.',
    howToWriteEachSection: [
      { section: 'Introduction', guidance: 'State why this review is needed now. What is the clinical/scientific problem? Why is existing evidence insufficient or confusing? State the scope and objectives of the review.' },
      { section: 'Body sections', guidance: 'Organize by themes, not by study. Each section: topic sentence stating the theme, synthesis of evidence, identification of consensus and controversy, your critical interpretation, transition to next theme.' },
      { section: 'Discussion/Conclusions', guidance: 'Synthesize across all sections. What is the current state of knowledge? What are the key controversies? What are the most important research gaps? What are practical implications?' },
    ],
    exampleResearchQuestions: [
      'What is the current evidence on the gut-brain axis in anxiety disorders?',
      'How has the management of septic shock evolved over the past decade?',
      'What are the proposed mechanisms of long COVID?',
    ],
    strengthsAndLimitations: {
      strengths: ['Flexible and efficient', 'Can cover broad complex topics', 'Expert interpretation adds value', 'Less resource-intensive than systematic review'],
      limitations: ['Susceptible to selection and confirmation bias', 'Not reproducible', 'Cannot be used for clinical guideline development', 'Evidence level is lower than systematic review'],
    },
    evidence_level: 'Level V (Expert Opinion)',
    timeRequired: '1-6 months',
    cost: 'Low',
    color: '#c9952a',
  },
  {
    id: 'umbrella-review',
    name: 'Umbrella Review',
    category: 'secondary',
    definition: 'A systematic review of systematic reviews (and meta-analyses) that collects and appraises multiple systematic reviews on a topic to provide the highest-level summary of evidence.',
    whenToUse: [
      'When multiple systematic reviews exist on overlapping questions',
      'For broad clinical questions with a large evidence base',
      'For guideline development requiring highest-level synthesis',
      'When comparing consistency of findings across systematic reviews',
      'Evaluating whether systematic reviews agree or contradict each other',
    ],
    whenNotToUse: [
      'When few or no systematic reviews exist (conduct a systematic review instead)',
      'For narrow specific questions with a single well-done systematic review',
    ],
    framework: 'PICO applied to systematic reviews as the unit of analysis',
    reportingGuideline: 'PRIOR checklist (Preferred Reporting Items for Overviews of Reviews)',
    reportingGuidelineUrl: 'equator-network.org/reporting-guidelines/prior',
    keySteps: [
      { step: 1, title: 'Register and define scope', description: 'Register in PROSPERO. Define which systematic reviews are eligible (with or without meta-analysis? All designs or RCTs only?).' },
      { step: 2, title: 'Search for systematic reviews', description: 'Search for systematic reviews and meta-analyses only. Use "systematic review" AND "[topic]" with study design filters in PubMed, Cochrane, EMBASE.' },
      { step: 3, title: 'Screen and select reviews', description: 'Apply eligibility criteria to identified systematic reviews. Two reviewers independently.' },
      { step: 4, title: 'Assess quality of systematic reviews', description: 'Use AMSTAR 2 (A MeaSurement Tool to Assess systematic Reviews) to appraise quality of each included systematic review.' },
      { step: 5, title: 'Extract and map overlapping evidence', description: 'Note which primary studies are shared across systematic reviews (overlap). Calculate corrected covered area (CCA) for overlap.' },
      { step: 6, title: 'Synthesize across reviews', description: 'Organize findings by PICO components. Note consistency/inconsistency of conclusions. Grade overall certainty.' },
    ],
    commonMistakes: [
      { mistake: 'Not assessing overlap between systematic reviews', consequence: 'Treats shared primary studies as independent; inflates apparent evidence', fix: 'Calculate and report Corrected Covered Area (CCA) using GROOVE tool' },
      { mistake: 'Using AMSTAR instead of AMSTAR 2', consequence: 'Outdated quality assessment; reviewers will flag this', fix: 'Use AMSTAR 2 (16 items, not the original 11-item AMSTAR)' },
      { mistake: 'Including narrative reviews', consequence: 'Methodological inconsistency; narrative reviews cannot be pooled with systematic reviews', fix: 'Include only PRISMA-compliant systematic reviews with explicit search methods' },
    ],
    sampleSizeConsiderations: 'Number of included systematic reviews varies. Minimum 3 systematic reviews needed to conduct a meaningful umbrella review. Calculate overlap: if CCA >15%, address redundancy explicitly.',
    statisticalApproach: 'Meta-meta-analysis (pooling estimates from multiple meta-analyses) is controversial. More commonly: tabular summary of pooled estimates from each systematic review, with AMSTAR 2 ratings. If meta-meta-analysis conducted: use three-level hierarchical model.',
    howToWriteEachSection: [
      { section: 'Introduction', guidance: 'Explain why an umbrella review is needed: multiple systematic reviews exist with potentially conflicting conclusions. State the broad PICO question.' },
      { section: 'Methods', guidance: 'State inclusion criteria explicitly (systematic reviews ± meta-analysis). Describe AMSTAR 2 quality assessment. Describe overlap assessment (CCA). Describe synthesis approach.' },
      { section: 'Results', guidance: 'PRISMA-type flow diagram for systematic reviews. AMSTAR 2 ratings for each review. Table: review, AMSTAR 2 rating, number of studies, key finding. CCA overlap figure. Synthesis of consistent vs. discordant findings.' },
    ],
    exampleResearchQuestions: [
      'What is the overall evidence on exercise interventions for depression across all patient populations?',
      'What do all existing systematic reviews conclude about the effectiveness of probiotics for IBD?',
    ],
    strengthsAndLimitations: {
      strengths: ['Highest level of secondary evidence', 'Efficiently summarizes a large evidence base', 'Identifies consistency/inconsistency across reviews'],
      limitations: ['Dependent entirely on quality of included systematic reviews', 'Overlap problem: same primary studies counted multiple times', 'May miss recent primary studies not yet included in any review'],
    },
    evidence_level: 'Level I (Summary of systematic reviews)',
    timeRequired: '6-12 months',
    cost: 'Medium',
    color: '#c94040',
  },
  {
    id: 'rct',
    name: 'Randomized Controlled Trial (RCT)',
    category: 'primary',
    definition: 'A prospective experimental study in which participants are randomly allocated to an intervention group or control group to assess the effect of an intervention while controlling for confounding.',
    whenToUse: [
      'Testing the efficacy of a treatment, drug, device, or intervention',
      'Establishing causal relationships between intervention and outcome',
      'When a control condition is ethical and feasible',
      'Phase II-III clinical trials',
      'Behavioral and educational interventions',
    ],
    whenNotToUse: [
      'When randomization is unethical (rare diseases, high-risk interventions)',
      'For rare exposures where recruitment is not feasible',
      'For questions about prognosis, etiology, or diagnosis',
      'When the intervention is irreversible (e.g., surgery for established disease)',
    ],
    framework: 'PICO (Population, Intervention, Comparison, Outcome) with pre-specified primary endpoint',
    reportingGuideline: 'CONSORT 2010 (+ extensions for specific designs)',
    reportingGuidelineUrl: 'consort-statement.org',
    keySteps: [
      { step: 1, title: 'Register in clinical trial registry', description: 'Register in ClinicalTrials.gov, ISRCTN, or WHO ICTRP BEFORE enrolling the first participant. Include primary endpoint, sample size, and analysis plan.' },
      { step: 2, title: 'Calculate sample size', description: 'Power calculation based on: expected effect size, standard deviation (or event rate), alpha (0.05), power (0.80 or 0.90). Document all assumptions.' },
      { step: 3, title: 'Develop randomization procedure', description: 'Use computer-generated allocation sequence. Consider stratified randomization for prognostic factors. Ensure allocation concealment (sealed envelopes, central randomization).' },
      { step: 4, title: 'Implement blinding', description: 'Blind participants, investigators, outcome assessors, and data analysts where possible. Document who was blinded and how. Address unblinding procedures.' },
      { step: 5, title: 'Conduct and monitor', description: 'Form an independent Data Safety Monitoring Board (DSMB) for trials >100 participants. Define stopping rules for harm and overwhelming efficacy.' },
      { step: 6, title: 'Analyze per protocol', description: 'Pre-specified primary analysis is intention-to-treat (ITT). Secondary: per-protocol analysis. Handle missing data with multiple imputation. Do NOT unblind early.' },
      { step: 7, title: 'Report using CONSORT 2010', description: 'Complete all 25 CONSORT checklist items. CONSORT flow diagram required. Report absolute risk differences, not just relative risk.' },
    ],
    commonMistakes: [
      { mistake: 'Registering after enrollment begins', consequence: 'High-impact journals (NEJM, Lancet) will reject outright; considered unethical', fix: 'Register BEFORE enrollment of first participant without exception' },
      { mistake: 'Inadequate allocation concealment', consequence: 'Selection bias; overestimates treatment effect by 30-40%', fix: 'Central telephone/web randomization or sequentially numbered sealed opaque envelopes' },
      { mistake: 'Analyzing as per-protocol without also doing ITT', consequence: 'Per-protocol alone introduces attrition bias', fix: 'Always report ITT as primary analysis; per-protocol as sensitivity analysis' },
      { mistake: 'Reporting only p-values without effect sizes and CIs', consequence: 'Clinically uninterpretable; rejected by most journals', fix: 'Report: treatment difference, 95% CI, NNT (for binary outcomes)' },
      { mistake: 'Multiple primary endpoints without adjustment', consequence: 'Type I error inflation; 5 comparisons at α=0.05 → 23% false positive rate', fix: 'Pre-specify ONE primary endpoint; use Bonferroni or Holm for multiple comparisons' },
    ],
    sampleSizeConsiderations: 'Formula: n = 2(Zα + Zβ)² × σ² / δ² for continuous outcomes. For binary: n = 2 × (Zα + Zβ)² × p̄(1-p̄) / δ². Standard assumptions: α=0.05, power=0.80, 20% dropout → inflate n by 25%. Justify effect size assumption with pilot data or prior literature.',
    statisticalApproach: 'Primary: Intention-to-treat analysis. Continuous outcomes: independent t-test or ANCOVA (adjusting for baseline). Binary: logistic regression or log-binomial. Time-to-event: Cox proportional hazards. Missing data: multiple imputation (not last observation carried forward). Pre-specify all subgroup analyses.',
    howToWriteEachSection: [
      { section: 'Abstract', guidance: 'CONSORT format: Background, Methods (design, setting, participants, interventions, primary outcome), Results (participants, primary result with CI and p-value, key harms), Conclusions. Include trial registration number.' },
      { section: 'Introduction', guidance: '2-3 paragraphs. Para 1: Disease burden and unmet need. Para 2: Current standard of care and its limitations. Para 3: Rationale for this intervention and this trial. End with primary hypothesis.' },
      { section: 'Methods', guidance: 'Follow CONSORT exactly: trial design, participants (eligibility criteria), interventions (dose, duration, fidelity), outcomes (primary + secondary with measurement instruments), sample size calculation, randomization (method + allocation concealment + implementation), blinding, statistical methods.' },
      { section: 'Results', guidance: 'CONSORT flow diagram. Baseline characteristics table (Table 1). Primary outcome first (with CI and p-value). Secondary outcomes. Subgroup analyses with interaction test. Adverse events table.' },
      { section: 'Discussion', guidance: 'Para 1: Principal findings in plain language. Para 2: Comparison with prior trials and systematic reviews. Para 3: Mechanisms. Para 4: Strengths. Para 5: Limitations (blinding success, dropout, generalizability). Para 6: Implications for practice and guidelines.' },
    ],
    exampleResearchQuestions: [
      'Does adding exercise to cognitive behavioral therapy reduce depression severity at 12 weeks vs. CBT alone?',
      'Does remote blood pressure monitoring reduce 6-month systolic BP vs. usual care in hypertensive patients?',
    ],
    strengthsAndLimitations: {
      strengths: ['Highest internal validity for causal questions', 'Randomization eliminates measured and unmeasured confounding', 'Gold standard for drug/intervention efficacy'],
      limitations: ['Expensive and time-consuming', 'Possible Hawthorne effect', 'May have limited generalizability (efficacy vs. effectiveness)', 'Not feasible for rare outcomes or long follow-up'],
    },
    evidence_level: 'Level II (single RCT); Level I when pooled in systematic review',
    timeRequired: '2-7 years',
    cost: 'High',
    color: '#2d6be4',
  },
  {
    id: 'cohort',
    name: 'Cohort Study',
    category: 'primary',
    definition: 'An observational study in which a group of people (the cohort) who share a defining characteristic are followed over time to examine outcomes. Can be prospective (forward-looking) or retrospective (using existing records).',
    whenToUse: [
      'Studying the natural history of a disease',
      'Examining multiple outcomes of a single exposure',
      'When RCT is unethical or infeasible',
      'Studying rare exposures but common outcomes',
      'Long-term outcomes requiring years of follow-up',
      'Generating incidence rates and relative risks',
    ],
    whenNotToUse: [
      'For rare outcomes (case-control is more efficient)',
      'Short-term outcomes that can be studied in an RCT',
      'When complete follow-up cannot be achieved',
    ],
    framework: 'Exposure → Follow-up period → Outcome (STROBE checklist)',
    reportingGuideline: 'STROBE (Strengthening the Reporting of Observational Studies in Epidemiology)',
    reportingGuidelineUrl: 'strobe-statement.org',
    keySteps: [
      { step: 1, title: 'Define cohort and exposure', description: 'Clearly define the cohort entry criteria. Define the exposure/risk factor with measurement timing. Define the index date (time zero).' },
      { step: 2, title: 'Assess confounders', description: 'Draw a Directed Acyclic Graph (DAG). Identify all confounders that must be measured. Plan how to measure them.' },
      { step: 3, title: 'Follow participants', description: 'Define follow-up procedures. Track loss to follow-up (aim <20%). Define censoring rules clearly.' },
      { step: 4, title: 'Measure outcomes', description: 'Blind outcome assessors to exposure status if possible. Use validated outcome definitions.' },
      { step: 5, title: 'Handle missing data', description: 'Multiple imputation for missing confounders. Complete case analysis as sensitivity. Report missing data rates.' },
      { step: 6, title: 'Analyze with appropriate adjustment', description: 'Cox regression for time-to-event outcomes. Logistic regression for binary. Address confounding: multivariable adjustment, propensity scores, or instrumental variables.' },
    ],
    commonMistakes: [
      { mistake: 'Not drawing a DAG for confounder selection', consequence: 'Over-adjustment (collider bias) or under-adjustment (residual confounding)', fix: 'Draw DAG using DAGitty.net; only adjust for confounders on the DAG' },
      { mistake: 'Loss to follow-up >20% without analysis', consequence: 'Attrition bias; may invalidate conclusions', fix: 'Report LTFU rate, compare characteristics of LTFU vs. retained, sensitivity analysis' },
      { mistake: 'Prevalent user bias in pharmacoepidemiology', consequence: 'Including existing drug users at cohort entry biases toward survivors', fix: 'Use incident new-user design; only enroll new initiators' },
      { mistake: 'Not accounting for time-varying confounding', consequence: 'Confounders that change with treatment/exposure introduce bias', fix: 'Use marginal structural models or G-estimation for time-varying confounders' },
    ],
    sampleSizeConsiderations: 'For binary outcomes: n = (Zα + Zβ)² × (p1(1-p1) + p2(1-p2)) / (p1-p2)². Rule of thumb for Cox regression: EPV (events per variable) ≥ 10 — i.e., 10 outcome events per covariate in the model.',
    statisticalApproach: 'Time-to-event: Kaplan-Meier curves, log-rank test, Cox proportional hazards regression. Binary: logistic regression, Poisson regression for risk ratios. Continuous: linear regression. Report: hazard ratios, risk ratios, or odds ratios with 95% CI. For confounding: multivariable regression, propensity score matching/weighting, inverse probability of treatment weighting (IPTW).',
    howToWriteEachSection: [
      { section: 'Methods — Participants', guidance: 'State: eligibility criteria (inclusion and exclusion), source of cohort (population-based, hospital, registry), recruitment period, index date definition, how exposure was measured and when.' },
      { section: 'Methods — Statistical', guidance: 'State confounders selected based on DAG. Describe imputation approach for missing data. List sensitivity analyses pre-specified: complete case, different confounder sets, alternative exposure definitions.' },
      { section: 'Results', guidance: 'Table 1: characteristics at baseline by exposure group. Unadjusted then adjusted estimates. Kaplan-Meier curve if survival outcome. Subgroup analyses. E-values for key results.' },
    ],
    exampleResearchQuestions: [
      'What is the 10-year risk of cardiovascular disease in adults with metabolic syndrome vs. without?',
      'Does long-term use of proton pump inhibitors increase risk of chronic kidney disease?',
    ],
    strengthsAndLimitations: {
      strengths: ['Can study multiple outcomes of one exposure', 'Temporal sequence established', 'Can calculate incidence rates', 'Suited to rare exposures'],
      limitations: ['Confounding (measured and unmeasured)', 'Expensive and time-consuming if prospective', 'Attrition bias from loss to follow-up', 'Cannot fully establish causation'],
    },
    evidence_level: 'Level III (observational)',
    timeRequired: '1-10 years (prospective); weeks-months (retrospective)',
    cost: 'Medium to High',
    color: '#0d9e6e',
  },
  {
    id: 'case-control',
    name: 'Case-Control Study',
    category: 'primary',
    definition: 'An observational study in which people with a disease/outcome (cases) are compared with people without it (controls) regarding past exposure to potential risk factors. Works backward from outcome to exposure.',
    whenToUse: [
      'Rare diseases or outcomes',
      'When a cohort study would take too long or cost too much',
      'Investigating multiple risk factors for one disease',
      'Disease outbreaks requiring rapid investigation',
      'Preliminary investigation before a cohort study',
    ],
    whenNotToUse: [
      'Cannot calculate incidence or risk directly (only odds ratio)',
      'When exposure data cannot be reliably recalled',
      'For diseases with very short latency periods',
    ],
    framework: 'Outcome → Case/Control selection → Exposure assessment',
    reportingGuideline: 'STROBE',
    reportingGuidelineUrl: 'strobe-statement.org',
    keySteps: [
      { step: 1, title: 'Define cases and controls', description: 'Case definition: clear diagnostic criteria, incident vs. prevalent, source population. Controls: must come from same source population as cases. Match on key confounders (age, sex, calendar time).' },
      { step: 2, title: 'Determine matching strategy', description: 'Individual matching (1:1 to 1:4) or frequency matching. More controls increases power. Risk of over-matching: do not match on variables on the causal pathway.' },
      { step: 3, title: 'Assess exposure', description: 'Use same method for cases and controls to avoid differential misclassification. Blind assessors to case/control status when measuring exposure.' },
      { step: 4, title: 'Identify confounders', description: 'Same DAG approach as cohort. Collect data on all identified confounders.' },
      { step: 5, title: 'Calculate sample size', description: 'Based on: expected OR, exposure prevalence in controls, alpha, power, matching ratio.' },
      { step: 6, title: 'Analyze using conditional logistic regression', description: 'For matched studies: conditional logistic regression. Unmatched: unconditional logistic regression. Report odds ratios with 95% CI.' },
    ],
    commonMistakes: [
      { mistake: 'Selecting controls from hospitals (when cases are community-based)', consequence: 'Berkson\'s bias: hospitalized controls may have different exposure profiles', fix: 'Controls must be sampled from the same population that gave rise to cases' },
      { mistake: 'Recall bias (cases remember exposures more than controls)', consequence: 'Overestimates association between exposure and disease', fix: 'Use objective records (pharmacy, hospital) rather than self-report when possible' },
      { mistake: 'Over-matching (matching on a collider)', consequence: 'Masks true association; reduces efficiency', fix: 'Only match on established confounders, not on variables that could be mediators' },
    ],
    sampleSizeConsiderations: 'n cases = (Zα + Zβ)² × (p1(1-p1)/r + p0(1-p0)) / (p1-p0)² where r = control:case ratio, p0 = exposure in controls, p1 = exposure in cases. Increasing controls beyond 1:4 adds minimal power.',
    statisticalApproach: 'Matched design: conditional logistic regression. Unmatched: unconditional logistic regression. Report odds ratios (OR) with 95% CI. Note: OR approximates RR only when disease is rare (<10%). Mantel-Haenszel method for stratified analysis.',
    howToWriteEachSection: [
      { section: 'Methods — Participants', guidance: 'State case definition (diagnostic criteria, incident vs. prevalent, setting). State how controls were identified and what exclusion criteria applied. State matching variables and ratio.' },
      { section: 'Results', guidance: 'Characteristics of cases vs. controls (Table 1). Unadjusted then adjusted ORs with 95% CI. If matched, confirm matching success. Subgroup analyses.' },
    ],
    exampleResearchQuestions: [
      'Are pesticide exposures associated with Parkinson\'s disease?',
      'What dietary factors are associated with colorectal cancer?',
    ],
    strengthsAndLimitations: {
      strengths: ['Efficient for rare diseases', 'Relatively quick and inexpensive', 'Can study multiple exposures simultaneously', 'Good for hypothesis generation'],
      limitations: ['Cannot directly calculate incidence or risk', 'Recall bias', 'Selection bias in control group', 'Cannot establish temporal sequence as clearly as cohort'],
    },
    evidence_level: 'Level III',
    timeRequired: '6 months - 2 years',
    cost: 'Low to Medium',
    color: '#c97d2a',
  },
  {
    id: 'cross-sectional',
    name: 'Cross-Sectional Study',
    category: 'primary',
    definition: 'An observational study that measures exposure and outcome at the same point in time in a defined population. Provides a "snapshot" of the population.',
    whenToUse: [
      'Estimating disease prevalence',
      'Identifying associations for hypothesis generation',
      'Assessing public health needs at a single time point',
      'Validating diagnostic tests (with STARD checklist)',
      'Health surveys and needs assessments',
    ],
    whenNotToUse: [
      'Establishing causal relationships (temporal ambiguity)',
      'Studying rare diseases or outcomes',
      'Diseases with short duration (point prevalence underestimates)',
    ],
    framework: 'STROBE for observational studies',
    reportingGuideline: 'STROBE',
    reportingGuidelineUrl: 'strobe-statement.org',
    keySteps: [
      { step: 1, title: 'Define population and sampling strategy', description: 'Define target population. Choose sampling: simple random, stratified random, cluster, or convenience. Calculate required sample size for prevalence estimation.' },
      { step: 2, title: 'Measure exposure and outcome simultaneously', description: 'Use validated measurement tools. Recognize that you cannot establish temporal sequence.' },
      { step: 3, title: 'Calculate prevalence', description: 'Point prevalence = cases at one time point / total population examined. Period prevalence over a time window.' },
      { step: 4, title: 'Analyze associations', description: 'Logistic regression for binary outcomes. Linear regression for continuous. Prevalence ratio preferred over odds ratio for common outcomes.' },
    ],
    commonMistakes: [
      { mistake: 'Claiming causal conclusions from cross-sectional data', consequence: 'Cannot determine if A caused B or B caused A', fix: 'Use language: "was associated with" never "caused" or "led to"' },
      { mistake: 'Using odds ratio for common outcomes', consequence: 'OR overestimates the prevalence ratio when prevalence >10%', fix: 'Use Poisson regression with robust variance to get prevalence ratios' },
      { mistake: 'Convenience sampling without acknowledgment', consequence: 'Results not generalizable; unrepresentative sample', fix: 'Use probability sampling when possible; describe sampling limitations explicitly' },
    ],
    sampleSizeConsiderations: 'For prevalence: n = Z² × p(1-p) / d² where p = expected prevalence, d = acceptable margin of error. For association: as for logistic regression — EPV ≥ 10 per covariate.',
    statisticalApproach: 'Descriptive: frequencies, proportions, means, SDs. Associations: logistic regression (OR) or Poisson regression (prevalence ratio, PR). Adjust for survey design if complex sampling used (survey-weighted analysis in R or Stata).',
    howToWriteEachSection: [
      { section: 'Methods', guidance: 'State: study period (single date or date range), sampling frame, sampling method, sample size calculation, measurement instruments with validation references, response rate.' },
      { section: 'Results', guidance: 'Participation flow diagram (invited → completed). Characteristics table. Prevalence estimates with 95% CI. Association table with unadjusted and adjusted estimates.' },
    ],
    exampleResearchQuestions: [
      'What is the prevalence of hypertension in adults aged 40-70 in urban Kenya?',
      'What factors are associated with burnout in medical students?',
    ],
    strengthsAndLimitations: {
      strengths: ['Quick and inexpensive', 'Provides prevalence data', 'No follow-up required', 'Can study multiple exposures and outcomes simultaneously'],
      limitations: ['Cannot establish temporal sequence or causation', 'Prevalent user bias', 'Healthy worker effect', 'Unsuitable for rare conditions'],
    },
    evidence_level: 'Level IV',
    timeRequired: '3-12 months',
    cost: 'Low',
    color: '#8b9ab0',
  },
  {
    id: 'mixed-methods',
    name: 'Mixed Methods Study',
    category: 'mixed',
    definition: 'Research that integrates quantitative and qualitative data collection and analysis, either concurrently or sequentially, to answer research questions that neither approach alone could address.',
    whenToUse: [
      'When quantitative data needs qualitative explanation (why did the intervention work/fail?)',
      'Developing and validating questionnaires (qualitative → quantitative)',
      'Complex intervention evaluation requiring both outcomes AND process data',
      'When stakeholder perspectives are needed to interpret clinical data',
      'Implementation science: how an intervention works in context',
    ],
    whenNotToUse: [
      'When the research question can be answered by one approach alone',
      'When resources are insufficient for two full studies',
      'When integration is superficial ("parallel play" studies)',
    ],
    framework: 'Based on design type: Convergent, Explanatory Sequential, Exploratory Sequential, or Embedded',
    reportingGuideline: 'MMAT (Mixed Methods Appraisal Tool) for quality; GRAMMS for reporting',
    reportingGuidelineUrl: 'mixedmethodsappraisaltoolpublic.pbworks.com',
    keySteps: [
      { step: 1, title: 'Choose design type', description: 'Convergent: collect QUAN and QUAL simultaneously, merge. Explanatory Sequential: QUAN first, then QUAL to explain. Exploratory Sequential: QUAL first, then QUAN to test. Embedded: one strand embedded in the other.' },
      { step: 2, title: 'Develop integration strategy', description: 'Define at which stage you will integrate: design, data collection, analysis, or interpretation? Integration is the defining feature of mixed methods.' },
      { step: 3, title: 'Address paradigm fit', description: 'Adopt pragmatism as philosophical foundation. Address how you will reconcile conflicting findings across QUAN and QUAL strands.' },
      { step: 4, title: 'Conduct each strand with full rigor', description: 'The quantitative strand must meet quantitative rigor standards. The qualitative strand must meet qualitative rigor standards (credibility, transferability, dependability).' },
      { step: 5, title: 'Integrate at analysis or interpretation', description: 'Convergent: joint display. Sequential: use findings from one strand to develop/explain the other. Report integration points explicitly.' },
    ],
    commonMistakes: [
      { mistake: 'No genuine integration — just two separate studies', consequence: 'Not mixed methods; reviewers will identify immediately', fix: 'Explicitly describe how QUAL and QUAN findings were integrated and what emerged from integration' },
      { mistake: 'Reporting only one strand in detail', consequence: 'Imbalanced reporting; the weaker strand undermines the paper', fix: 'Both strands must meet their own quality standards and be reported fully' },
      { mistake: 'Using "qualitative" methods for quantitative goals', consequence: 'Methodological inconsistency; e.g., using thematic analysis to calculate frequencies', fix: 'Align questions, methods, and analysis within each strand' },
    ],
    sampleSizeConsiderations: 'Quantitative strand: standard power calculation for design. Qualitative strand: theoretical saturation (typically 8-25 interviews or until no new themes emerge). These are separate decisions.',
    statisticalApproach: 'Quantitative: appropriate statistical tests for design. Qualitative: thematic analysis, framework analysis, grounded theory, or content analysis. Integration: joint display matrix comparing QUAL themes with QUAN results; typology development; building explanatory model.',
    howToWriteEachSection: [
      { section: 'Introduction', guidance: 'Justify mixed methods: why do you need both strands? What can\'t one approach answer? State the design type and integration rationale.' },
      { section: 'Methods', guidance: 'Separate QUAN and QUAL methods subsections. Then: Integration section — state where/how strands were integrated. Include a visual diagram of the design.' },
      { section: 'Results', guidance: 'Present each strand separately first. Then: Integration section — joint display, convergence/divergence analysis, emergent insights from integration.' },
      { section: 'Discussion', guidance: 'Discuss integrated findings, not separate strands. Explain what the integration revealed that neither strand could alone.' },
    ],
    exampleResearchQuestions: [
      'How effective is a peer support intervention for depression (QUAN: RCT), and how do participants experience it (QUAL: interviews)? — Embedded design',
      'What barriers do nurses face in using a new EHR system (QUAL), and how prevalent are these barriers (QUAN: survey)? — Exploratory sequential',
    ],
    strengthsAndLimitations: {
      strengths: ['Addresses complex real-world questions comprehensively', 'Quantitative and qualitative findings triangulate each other', 'Can explain unexpected quantitative findings', 'More complete picture of intervention mechanisms'],
      limitations: ['Resource and time intensive', 'Requires expertise in both approaches', 'Integration is methodologically challenging', 'Difficult to find journals that welcome mixed methods'],
    },
    evidence_level: 'Varies by component; integration provides added insight',
    timeRequired: '1-4 years',
    cost: 'Medium to High',
    color: '#c9952a',
  },
  {
    id: 'qualitative',
    name: 'Qualitative Study',
    category: 'qualitative',
    definition: 'Research that generates non-numerical data to understand meanings, experiences, and perspectives. Multiple methodologies exist (grounded theory, phenomenology, ethnography, thematic analysis, content analysis).',
    whenToUse: [
      'Understanding how or why something happens, not just whether it does',
      'Exploring lived experience of a condition or intervention',
      'Theory development in an understudied area',
      'Patient or clinician perspectives on care',
      'Identifying barriers and facilitators to implementation',
      'When existing frameworks may not capture the phenomenon',
    ],
    whenNotToUse: [
      'When you need prevalence estimates or effect sizes',
      'When a hypothesis needs testing',
      'When generalizability to a large population is the goal',
    ],
    framework: 'Depends on methodology: IPA, GT, TA, etc.',
    reportingGuideline: 'COREQ (Consolidated criteria for Reporting Qualitative research) — 32 items',
    reportingGuidelineUrl: 'equator-network.org/reporting-guidelines/coreq',
    keySteps: [
      { step: 1, title: 'Choose methodology', description: 'Grounded Theory: theory development from data. Phenomenology/IPA: lived experience. Ethnography: culture/context. Thematic Analysis: flexible, patterns across data. Framework Analysis: applied policy context. Choose based on epistemological position.' },
      { step: 2, title: 'Purposive sampling', description: 'Sample for theoretical richness, not representativeness. Purposive, maximum variation, or theoretical sampling. Recruit until data saturation or theoretical saturation.' },
      { step: 3, title: 'Data collection', description: 'In-depth interviews (individual or focus group). Topic guide (semi-structured). Audio record and transcribe verbatim. Member checking if appropriate.' },
      { step: 4, title: 'Rigorous analysis', description: 'Thematic Analysis: familiarization → codes → themes → review → define → write. Grounded Theory: open, axial, selective coding. Audit trail of analytical decisions required.' },
      { step: 5, title: 'Establish trustworthiness', description: 'Credibility: member checking, prolonged engagement. Transferability: thick description. Dependability: audit trail. Confirmability: reflexivity statement.' },
    ],
    commonMistakes: [
      { mistake: 'Reporting frequency counts from qualitative data', consequence: 'Misunderstands qualitative epistemology; undermines findings', fix: 'Report themes and meaning, not how many people said something' },
      { mistake: 'Stopping at n=5 interviews without saturation', consequence: 'Premature closure; themes may not be fully developed', fix: 'Continue data collection until no new themes emerge (typically 12-25 interviews)' },
      { mistake: 'No reflexivity statement', consequence: 'Fails COREQ item 6; how researcher\'s position shaped interpretation unknown', fix: 'State researcher\'s disciplinary background, relationship to topic, prior assumptions' },
      { mistake: 'Using "thematic analysis" without specifying the approach', consequence: 'Thematic analysis has at least 6 different frameworks — specify Braun & Clarke or other', fix: 'State: "We used reflexive thematic analysis following Braun & Clarke (2006)"' },
    ],
    sampleSizeConsiderations: 'Determined by saturation, not statistical power. For thematic analysis: 8-25 interviews typical. IPA: 3-8 participants (ideally homogeneous sample). Grounded theory: 20-30+ until theoretical saturation. Focus groups: 4-8 per group, 3-5 groups minimum.',
    statisticalApproach: 'No statistical tests. Analysis approaches: thematic analysis (Braun & Clarke), framework analysis, interpretive phenomenological analysis (IPA), grounded theory (Strauss & Corbin or Charmaz constructivist GT), content analysis (manifest or latent). NVivo or Atlas.ti commonly used for coding.',
    howToWriteEachSection: [
      { section: 'Methods', guidance: 'COREQ checklist covers all required elements: research team, study design, participant selection, context, data collection (interview guide, duration), and data analysis approach. Include reflexivity statement.' },
      { section: 'Results', guidance: 'Present themes with: theme name, description, illustrative quotes (with participant identifier, not name). Do NOT present as a list of quotes — integrate quotes into analytical narrative. Use overarching/subtheme structure.' },
      { section: 'Discussion', guidance: 'Integrate findings with existing literature. Discuss theoretical implications. Address transferability (to whom might findings apply?). State reflexivity position and how it may have shaped interpretation.' },
    ],
    exampleResearchQuestions: [
      'How do patients with chronic pain experience the transition from opioid therapy?',
      'What are the barriers and facilitators to implementing sepsis protocols in community hospitals?',
    ],
    strengthsAndLimitations: {
      strengths: ['Rich, context-sensitive understanding', 'Generates theory', 'Captures patient and clinician voice', 'Explains the "how" and "why"'],
      limitations: ['Not generalizable by design', 'Time-intensive data collection and analysis', 'Cannot be replicated exactly', 'Subjectivity of researcher embedded in analysis'],
    },
    evidence_level: 'Qualitative evidence (separate hierarchy)',
    timeRequired: '6-18 months',
    cost: 'Low to Medium',
    color: '#7a5c1a',
  },
];

export function getStudyTypeById(id: string): StudyType | undefined {
  return STUDY_TYPES.find(s => s.id === id);
}

export function getStudyTypesByCategory(category: StudyType['category']): StudyType[] {
  return STUDY_TYPES.filter(s => s.category === category);
}
